### ISSUE TITLE
“Error on dataset load, continuing” when set MFT as modeltype

### ISSUE THREAD

**Issue by G1tQuality** [athaddius/STIRMetrics#10]
First of all, congratulations on the successful organization of the STIR challenge!!

When reproducing the MFT tracking method, I met an error related to loading dataset: https://github.com/athaddius/STIRMetrics/blob/5e79b195838f7e7aa3d1ef7c81d32d5280fce324/src/datatest/flow2d.py#L257             print(f"error on dataset load, continuing")

The only modification I made was to comment the 'with importlib ...' line as I am using Python 3.7 while the `files` function is introduced in Python 3.9
`def load_config(path):
    """ https://stackoverflow.com/a/67692 """
    import importlib.util
    import importlib
    # with importlib.resources.files(__package__) as package_path: # https://stackoverflow.com/questions/6028000/how-to-read-a-static-file-from-inside-a-python-package?noredirect=1&lq=1
    path = Path(path)
    assert Path(path).exists(), f"config {path} does not exist!"
    spec = importlib.util.spec_from_file_location("tracker_config", path)
    foo = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(foo)
    return foo.get_config(package_path)`

Meanwhile, I remember that there was a MFT_STIR repo previously, which I git cloned and used here. I think this repo is missing becasue the link in the ReadMe currently directs to STIRLoader.

However, I have already reproduced the CSRT method and got almost the same results you provided (70.6 mean EPE and its accuracy). 

I'd appreciate it if you could give me any advice!!

**Comment by athaddius** [comment]
Thank you!
I would guess the reason for this error is that MFT is not installed. You should be able to install it here at [MFT_STIR](https://github.com/athaddius/MFT_STIR). We need to update the code to provide more informative error messages in future iterations.
We will fix the link on the wiki now.
