### ISSUE TITLE
ModuleNotFoundError: No module named 'MFT'

### ISSUE THREAD

**Issue by MichaelWangGo** [athaddius/STIRMetrics#6]
Hi authors, thanks for your code, but I met this error when I excuted `python datatest/clicktracks.py --num_data 3`
 File "/workspace/STIRMetrics/src/datatest/mft.py", line 2, in <module>
    from MFT.config import load_config
ModuleNotFoundError: No module named 'MFT'

**Comment by athaddius** [comment]
Totally, this is the MFT tracker. We provide an adapter here: [MFT_STIR](https://github.com/athaddius/MFT_STIR) that can be pip installed. Alternatively, you could comment all lines mentioning MFT if you prefer to use just RAFT or CSRT.
