### ISSUE TITLE
Missing sample in write2dgtjson.py when num_data=-1 ?

### ISSUE THREAD

**Issue by hassony2** [athaddius/STIRMetrics#9]
Hi !

I think there is a small bug in the script when num_data is set to -1.
I believe the intended effect is to evaluate on all samples in this case, but currently it is [skipping the last one](https://github.com/athaddius/STIRMetrics/blob/0b9be8b935dd6d548cae69ff46a85ce9f8a1d71f/src/datatest/write2dgtjson.py#L73).

Let me know if my understanding is correct :)

**Comment by athaddius** [comment]
Totally correct, thanks for finding this. It should now be fixed, but please re-open if you find it elsewhere.
